export const CREATE_FORM = "fieldy/CREATE_FORM"
export const REMOVE_FORM = "fieldy/REMOVE_FORM"
export const RESET_FORM = "fieldy/RESET_FORM"
export const SET_FORM_FIELDS = "fieldy/SET_FORM_FIELDS"
export const ADD_FORM_FIELDS = "fieldy/ADD_FORM_FIELDS"
export const REMOVE_FORM_FIELD = "fieldy/REMOVE_FORM_FIELD"
//export const SET_FORM_FLAT_VALUE = "fieldy/SET_FORM_FLAT_VALUE"
export const SET_FORM_INITIAL_VALUE = "fieldy/SET_FORM_INITIAL_VALUE"
//export const SET_FORM_DEFAULT_VALUE = "fieldy/SET_FORM_DEFAULT_VALUE"
export const SET_FORM_VALUE = "fieldy/SET_FORM_VALUE"
export const SET_FORM_INITIALIZED_FLAG = "fieldy/SET_FORM_INITIALIZED_FLAG"
export const SET_FORM_FIELDS_FEEDBACKS = "fieldy/SET_FORM_FIELDS_FEEDBACKS"

//Field actions
export const SET_FIELD_INITIAL_VALUE = "fieldy/SET_FIELD_INITIAL_VALUE"
export const SET_FIELD_VALUE = "fieldy/SET_FIELD_VALUE"
export const INPUT_FIELD_VALUE = "fieldy/INPUT_FIELD_VALUE"
export const SET_FIELD_DEFAULT_VALUE = "fieldy/SET_FIELD_DEFAULT_VALUE"
export const SET_FIELD_STATE = "fieldy/SET_FIELD_STATE"
export const CLEAR_FIELD_ERRORS = "fieldy/CLEAR_FIELD_ERRORS"

//export const SET_MULTI_FIELD_VALUES = "fieldy/SET_MULTI_FIELD_VALUES"