export default{
  widget:'OptionRowGroup',
  group:'margin',
  xs:{
    label:'Margin Left',
    isFirst:true,
    widget:'OpSelect',
    list:{
      'ml-0':'0',
      'ml-1':'1',
      'ml-2':'2',
      'ml-3':'3',
      'ml-4':'4',
      'ml-5':'5',
    },
  },
  //---------------------
  sm:{
    label:'SM',
    widget:'OpSelect',
    list:{
      'ml-sm-0':'0',
      'ml-sm-1':'1',
      'ml-sm-2':'2',
      'ml-sm-3':'3',
      'ml-sm-4':'4',
      'ml-sm-5':'5',
    },
  },
  //---------------------
  md:{
    label:'MD',
    widget:'OpSelect',
    list:{
      'ml-md-0':'0',
      'ml-md-1':'1',
      'ml-md-2':'2',
      'ml-md-3':'3',
      'ml-md-4':'4',
      'ml-md-5':'5',
    },
  },
  //---------------------
  lg:{
    label:'LG',
    widget:'OpSelect',
    list:{
      'ml-lg-0':'0',
      'ml-lg-1':'1',
      'ml-lg-2':'2',
      'ml-lg-3':'3',
      'ml-lg-4':'4',
      'ml-lg-5':'5',
    },
  },
  //---------------------
  xl:{
    label:'XL',
    widget:'OpSelect',
    list:{
      'ml-xl-0':'0',
      'ml-xl-1':'1',
      'ml-xl-2':'2',
      'ml-xl-3':'3',
      'ml-xl-4':'4',
      'ml-xl-5':'5',
    },
  },
  //---------------------
}//<--marginH