export default{
  group:'margin',
  isResponsive:true,
  xs:{
    label:'Margin(H)',
    widget:'OpSelect',
    list:{
      'mx-0':'0',
      'mx-1':'1',
      'mx-2':'2',
      'mx-3':'3',
      'mx-4':'4',
      'mx-5':'5',
    },
  },
  //---------------------
  sm:{
    label:'Margin(H)',
    widget:'OpSelect',
    list:{
      'mx-sm-0':'0',
      'mx-sm-1':'1',
      'mx-sm-2':'2',
      'mx-sm-3':'3',
      'mx-sm-4':'4',
      'mx-sm-5':'5',
    },
  },
  //---------------------
  md:{
    label:'Margin(H)',
    widget:'OpSelect',
    list:{
      'mx-md-0':'0',
      'mx-md-1':'1',
      'mx-md-2':'2',
      'mx-md-3':'3',
      'mx-md-4':'4',
      'mx-md-5':'5',
    },
  },
  //---------------------
  lg:{
    label:'Margin(H)',
    widget:'OpSelect',
    list:{
      'mx-lg-0':'0',
      'mx-lg-1':'1',
      'mx-lg-2':'2',
      'mx-lg-3':'3',
      'mx-lg-4':'4',
      'mx-lg-5':'5',
    },
  },
  //---------------------
  xl:{
    label:'Margin(H)',
    widget:'OpSelect',
    list:{
      'mx-xl-0':'0',
      'mx-xl-1':'1',
      'mx-xl-2':'2',
      'mx-xl-3':'3',
      'mx-xl-4':'4',
      'mx-xl-5':'5',
    },
  },
  //---------------------
}//<--marginH