export default{
  isResponsive:true,
  xs:{
    label:'Right',
    widget:'OpSelect',
    list:{
      'mr-0':'0',
      'mr-1':'1',
      'mr-2':'2',
      'mr-3':'3',
      'mr-4':'4',
      'mr-5':'5',
    },
  },
  //---------------------
  sm:{
    label:'Right',
    widget:'OpSelect',
    list:{
      'mr-sm-0':'0',
      'mr-sm-1':'1',
      'mr-sm-2':'2',
      'mr-sm-3':'3',
      'mr-sm-4':'4',
      'mr-sm-5':'5',
    },
  },
  //---------------------
  md:{
    label:'Right',
    widget:'OpSelect',
    list:{
      'mr-md-0':'0',
      'mr-md-1':'1',
      'mr-md-2':'2',
      'mr-md-3':'3',
      'mr-md-4':'4',
      'mr-md-5':'5',
    },
  },
  //---------------------
  lg:{
    label:'Right',
    widget:'OpSelect',
    list:{
      'mr-lg-0':'0',
      'mr-lg-1':'1',
      'mr-lg-2':'2',
      'mr-lg-3':'3',
      'mr-lg-4':'4',
      'mr-lg-5':'5',
    },
  },
  //---------------------
  xl:{
    label:'Right',
    widget:'OpSelect',
    list:{
      'mr-xl-0':'0',
      'mr-xl-1':'1',
      'mr-xl-2':'2',
      'mr-xl-3':'3',
      'mr-xl-4':'4',
      'mr-xl-5':'5',
    },
  },
  //---------------------
}//<--marginH