export const CREATE_FORM = "fieldy/CREATE_FORM"
export const REMOVE_FORM = "fieldy/REMOVE_FORM"
export const SET_FORM_FIELDS = "fieldy/SET_FORM_FIELDS"
export const SET_FORM_FLAT_VALUES = "fieldy/SET_FORM_FLAT_VALUES"
export const SET_FORM_INITIAL_VALUES = "fieldy/SET_FORM_INITIAL_VALUES"
export const SET_FORM_VALUES = "fieldy/SET_FORM_VALUES"
export const SET_FORM_INITIALZED_FLAG = "fieldy/SET_FORM_INITIALZED_FLAG"