export default{
  fieldName:'classList',
  label:'Contextual',
  widget:'OpSelect',
  defaultValue:'',
  list:{
    'btn-primary':'Primary',
    'btn-secondary':'Secondary',
    'btn-success':'Success',
    'btn-danger':'Danger',
    'btn-warning':'Warning',
    'btn-info':'Info',
    'btn-light':'Light',
    'btn-dark':'Dark',

    'btn-outline-primary':'Outline Primary',
    'btn-outline-secondary':'Outline Secondary',
    'btn-outline-success':'Outline Success',
    'btn-outline-danger':'Outline Danger',
    'btn-outline-warning':'Outline Warning',
    'btn-outline-info':'Outline Info',
    'btn-outline-light':'Outline Light',
    'btn-outline-dark':'Outline Dark',
  },
}