export default{
  fieldName:'classList',
  isResponsive:true,
  xs:{
    label:'Responsive',
    widget:'OpSwitch',
    onValue:'table-responsive',
    offValue:'',
    defaultValue:'',
  },
  //---------------------
  sm:{
    label:'Responsive',
    widget:'OpSwitch',
    onValue:'table-responsive-sm',
    offValue:'',
    defaultValue:'',
  },
  //---------------------
  md:{
    label:'Responsive',
    widget:'OpSwitch',
    onValue:'table-responsive-md',
    offValue:'',
    defaultValue:'',
  },
  //---------------------
  lg:{
    label:'Responsive',
    widget:'OpSwitch',
    onValue:'table-responsive-lg',
    offValue:'',
    defaultValue:'',
  },
  //---------------------
  xl:{
    label:'Responsive',
    widget:'OpSwitch',
    onValue:'table-responsive-xl',
    offValue:'',
    defaultValue:'',
  },
  //---------------------
}