export default{
  fieldName:'classList',
  isResponsive:true,
  xs:{
    widget:'OpSwitch',
    label:'Fill',
    onValue:'flex-fill',
    offValue:'',
    defaultValue:'',
  },
  //---------------------
  sm:{
    widget:'OpSwitch',
    label:'Fill',
    onValue:'flex-fill',
    offValue:'',
    defaultValue:'',
  },
  //---------------------
  md:{
    widget:'OpSwitch',
    label:'Fill',
    onValue:'flex-fill',
    offValue:'',
    defaultValue:'',
  },
  //---------------------
  lg:{
    widget:'OpSwitch',
    label:'Fill',
    onValue:'flex-fill',
    offValue:'',
    defaultValue:'',
  },
  //---------------------
  xl:{
    widget:'OpSwitch',
    label:'Fill',
    onValue:'flex-fill',
    offValue:'',
    defaultValue:'',
  },
}