export default{
  widget:'OpSwitch',
  isResponsive:true,
  xs:{
    widget:'OpSelect',
    label:'Fill',
    list:{
      onValue:'flex-fill',
      offValue:'',
      defaultValue:'',
    },
  },
  //---------------------
  sm:{
    widget:'OpSelect',
    label:'Fill',
    list:{
      onValue:'flex-sm-fill',
      offValue:'',
      defaultValue:'',
    },
  },
  //---------------------
  md:{
    widget:'OpSelect',
    label:'Fill',
    list:{
      onValue:'flex-md-fill',
      offValue:'',
      defaultValue:'',
    },
  },
  //---------------------
  lg:{
    widget:'OpSelect',
    label:'Fill',
    list:{
      onValue:'flex-lg-fill',
      offValue:'',
      defaultValue:'',
    },
  },
  //---------------------
  xl:{
    widget:'OpSelect',
    label:'Fill',
    list:{
      onValue:'flex-xl-fill',
      offValue:'',
      defaultValue:'',
    },
  },
}