export default{
  widget:'OptionRowGroup',
  group:'dimension',
  xs:{
    label:'Margin(V)',
    isFirst:true,
    widget:'OpSelect',
    list:{
      'my-0':'0',
      'my-1':'1',
      'my-2':'2',
      'my-3':'3',
      'my-4':'4',
      'my-5':'5',
    },
  },
  //---------------------
  sm:{
    label:'SM',
    widget:'OpSelect',
    list:{
      'my-sm-0':'0',
      'my-sm-1':'1',
      'my-sm-2':'2',
      'my-sm-3':'3',
      'my-sm-4':'4',
      'my-sm-5':'5',
    },
  },
  //---------------------
  md:{
    label:'MD',
    widget:'OpSelect',
    list:{
      'my-md-0':'0',
      'my-md-1':'1',
      'my-md-2':'2',
      'my-md-3':'3',
      'my-md-4':'4',
      'my-md-5':'5',
    },
  },
  //---------------------
  lg:{
    label:'LG',
    widget:'OpSelect',
    list:{
      'my-lg-0':'0',
      'my-lg-1':'1',
      'my-lg-2':'2',
      'my-lg-3':'3',
      'my-lg-4':'4',
      'my-lg-5':'5',
    },
  },
  //---------------------
  xl:{
    label:'XL',
    widget:'OpSelect',
    list:{
      'my-xl-0':'0',
      'my-xl-1':'1',
      'my-xl-2':'2',
      'my-xl-3':'3',
      'my-xl-4':'4',
      'my-xl-5':'5',
    },
  },
  //---------------------
}//<--marginV
