export default{
  widget:'OptionRowGroup',
  group:'margin',
  xs:{
    label:'Margin All',
    isFirst:true,
    widget:'OpSelect',
    list:{
      'm-0':'0',
      'm-1':'1',
      'm-2':'2',
      'm-3':'3',
      'm-4':'4',
      'm-5':'5',
    },
  },
  //---------------------
  sm:{
    label:'SM',
    widget:'OpSelect',
    list:{
      'm-sm-0':'0',
      'm-sm-1':'1',
      'm-sm-2':'2',
      'm-sm-3':'3',
      'm-sm-4':'4',
      'm-sm-5':'5',
    },
  },
  //---------------------
  md:{
    label:'MD',
    widget:'OpSelect',
    list:{
      'm-md-0':'0',
      'm-md-1':'1',
      'm-md-2':'2',
      'm-md-3':'3',
      'm-md-4':'4',
      'm-md-5':'5',
    },
  },
  //---------------------
  lg:{
    label:'LG',
    widget:'OpSelect',
    list:{
      'm-lg-0':'0',
      'm-lg-1':'1',
      'm-lg-2':'2',
      'm-lg-3':'3',
      'm-lg-4':'4',
      'm-lg-5':'5',
    },
  },
  //---------------------
  xl:{
    label:'XL',
    widget:'OpSelect',
    list:{
      'm-xl-0':'0',
      'm-xl-1':'1',
      'm-xl-2':'2',
      'm-xl-3':'3',
      'm-xl-4':'4',
      'm-xl-5':'5',
    },
  },
  //---------------------
}//