export default{
  widget:'OptionRowGroup',
  group:'margin',
  xs:{
    label:'Margin Bottom',
    isFirst:true,
    widget:'OpSelect',
    list:{
      'mb-0':'0',
      'mb-1':'1',
      'mb-2':'2',
      'mb-3':'3',
      'mb-4':'4',
      'mb-5':'5',
    },
  },
  //---------------------
  sm:{
    label:'SM',
    widget:'OpSelect',
    list:{
      'mb-sm-0':'0',
      'mb-sm-1':'1',
      'mb-sm-2':'2',
      'mb-sm-3':'3',
      'mb-sm-4':'4',
      'mb-sm-5':'5',
    },
  },
  //---------------------
  md:{
    label:'MD',
    widget:'OpSelect',
    list:{
      'mb-md-0':'0',
      'mb-md-1':'1',
      'mb-md-2':'2',
      'mb-md-3':'3',
      'mb-md-4':'4',
      'mb-md-5':'5',
    },
  },
  //---------------------
  lg:{
    label:'LG',
    widget:'OpSelect',
    list:{
      'mb-lg-0':'0',
      'mb-lg-1':'1',
      'mb-lg-2':'2',
      'mb-lg-3':'3',
      'mb-lg-4':'4',
      'mb-lg-5':'5',
    },
  },
  //---------------------
  xl:{
    label:'XL',
    widget:'OpSelect',
    list:{
      'mb-xl-0':'0',
      'mb-xl-1':'1',
      'mb-xl-2':'2',
      'mb-xl-3':'3',
      'mb-xl-4':'4',
      'mb-xl-5':'5',
    },
  },
  //---------------------
}//<--marginH