export default{
  widget:'OptionRowGroup',
  group:'padding',
  xs:{
    label:'Padding Right',
    isFirst:true,
    widget:'OpSelect',
    list:{
      'pr-0':'0',
      'pr-1':'1',
      'pr-2':'2',
      'pr-3':'3',
      'pr-4':'4',
      'pr-5':'5',
    },
  },
  //---------------------
  sm:{
    label:'SM',
    widget:'OpSelect',
    list:{
      'pr-sm-0':'0',
      'pr-sm-1':'1',
      'pr-sm-2':'2',
      'pr-sm-3':'3',
      'pr-sm-4':'4',
      'pr-sm-5':'5',
    },
  },
  //---------------------
  md:{
    label:'MD',
    widget:'OpSelect',
    list:{
      'pr-md-0':'0',
      'pr-md-1':'1',
      'pr-md-2':'2',
      'pr-md-3':'3',
      'pr-md-4':'4',
      'pr-md-5':'5',
    },
  },
  //---------------------
  lg:{
    label:'LG',
    widget:'OpSelect',
    list:{
      'pr-lg-0':'0',
      'pr-lg-1':'1',
      'pr-lg-2':'2',
      'pr-lg-3':'3',
      'pr-lg-4':'4',
      'pr-lg-5':'5',
    },
  },
  //---------------------
  xl:{
    label:'XL',
    widget:'OpSelect',
    list:{
      'pr-xl-0':'0',
      'pr-xl-1':'1',
      'pr-xl-2':'2',
      'pr-xl-3':'3',
      'pr-xl-4':'4',
      'pr-xl-5':'5',
    },
  },
  //---------------------
}//<--marginH