export default{
  widget:'OptionRowGroup',
  group:'padding',
  xs:{
    label:'Padding Bottom',
    isFirst:true,
    widget:'OpSelect',
    list:{
      'pb-0':'0',
      'pb-1':'1',
      'pb-2':'2',
      'pb-3':'3',
      'pb-4':'4',
      'pb-5':'5',
    },
  },
  //---------------------
  sm:{
    label:'SM',
    widget:'OpSelect',
    list:{
      'pb-sm-0':'0',
      'pb-sm-1':'1',
      'pb-sm-2':'2',
      'pb-sm-3':'3',
      'pb-sm-4':'4',
      'pb-sm-5':'5',
    },
  },
  //---------------------
  md:{
    label:'MD',
    widget:'OpSelect',
    list:{
      'pb-md-0':'0',
      'pb-md-1':'1',
      'pb-md-2':'2',
      'pb-md-3':'3',
      'pb-md-4':'4',
      'pb-md-5':'5',
    },
  },
  //---------------------
  lg:{
    label:'LG',
    widget:'OpSelect',
    list:{
      'pb-lg-0':'0',
      'pb-lg-1':'1',
      'pb-lg-2':'2',
      'pb-lg-3':'3',
      'pb-lg-4':'4',
      'pb-lg-5':'5',
    },
  },
  //---------------------
  xl:{
    label:'XL',
    widget:'OpSelect',
    list:{
      'pb-xl-0':'0',
      'pb-xl-1':'1',
      'pb-xl-2':'2',
      'pb-xl-3':'3',
      'pb-xl-4':'4',
      'pb-xl-5':'5',
    },
  },
  //---------------------
}//<--marginH