export default{
   widget:'OptionRowGroup',
   group:'rowOptions',
   xs:{
     label:'Align Cols(V)',
     isFirst:true,
     widget:'OpSelect',
     list:{
       'align-items-start':'Start',
       'align-items-end':'End',
       'align-items-center':'Center',
       'align-items-baseline':'Between',
       'align-items-stretch':'Around',
     },
   },
   //---------------------
   sm:{
     label:'SM',
     widget:'OpSelect',
     list:{
       'align-items-sm-start':'Start',
       'align-items-sm-end':'End',
       'align-items-sm-center':'Center',
       'align-items-sm-baseline':'Between',
       'align-items-sm-stretch':'Around',
     },
   },
   //---------------------
   md:{
     label:'MD',
     widget:'OpSelect',
     list:{
       'align-items-md-start':'Start',
       'align-items-md-end':'End',
       'align-items-md-center':'Center',
       'align-items-md-baseline':'Between',
       'align-items-md-stretch':'Around',
     },
   },
   //---------------------
   lg:{
     label:'LG',
     widget:'OpSelect',
     list:{
       'align-items-lg-start':'Start',
       'align-items-lg-end':'End',
       'align-items-lg-center':'Center',
       'align-items-lg-baseline':'Between',
       'align-items-lg-stretch':'Around',
     },
   },
   //---------------------
   xl:{
     label:'XL',
     widget:'OpSelect',
     list:{
       'align-items-xl-start':'Start',
       'align-items-xl-end':'End',
       'align-items-xl-center':'Center',
       'align-items-xl-baseline':'Between',
       'align-items-xl-stretch':'Around',
     },
   },
   //---------------------
 }//<--vAlign