export default{
  fieldName:'classList',
  group:'utilities',
  isResponsive:true,
  xs:{
    label:'Float',
    widget:'OpSelect',
    list:{
      'float-left':'Left',
      'float-right':'Right',
      'float-none':'None',
    },
  },
  //---------------------
  sm:{
    label:'Float',
    widget:'OpSelect',
    list:{
      'float-sm-left':'Left',
      'float-sm-right':'Right',
      'float-sm-none':'None',
    },
  },
  //---------------------
  md:{
    label:'Float',
    widget:'OpSelect',
    list:{
      'float-md-left':'Left',
      'float-md-right':'Right',
      'float-md-none':'None',
    },
  },
  //---------------------
  lg:{
    label:'Float',
    widget:'OpSelect',
    list:{
      'float-lg-left':'Left',
      'float-lg-right':'Right',
      'float-lg-none':'None',
    },
  },
  //---------------------
  xl:{
    label:'Float',
    widget:'OpSelect',
    list:{
      'float-xl-left':'Left',
      'float-xl-right':'Right',
      'float-xl-none':'None',
    },
  },
  //---------------------
}