export default{
  isResponsive:true,
  xs:{
    label:'All',
    widget:'OpSelect',
    list:{
      'p-0':'0',
      'p-1':'1',
      'p-2':'2',
      'p-3':'3',
      'p-4':'4',
      'p-5':'5',
    },
  },
  //---------------------
  sm:{
    label:'All',
    widget:'OpSelect',
    list:{
      'p-sp-0':'0',
      'p-sp-1':'1',
      'p-sp-2':'2',
      'p-sp-3':'3',
      'p-sp-4':'4',
      'p-sp-5':'5',
    },
  },
  //---------------------
  md:{
    label:'All',
    widget:'OpSelect',
    list:{
      'p-md-0':'0',
      'p-md-1':'1',
      'p-md-2':'2',
      'p-md-3':'3',
      'p-md-4':'4',
      'p-md-5':'5',
    },
  },
  //---------------------
  lg:{
    label:'All',
    widget:'OpSelect',
    list:{
      'p-lg-0':'0',
      'p-lg-1':'1',
      'p-lg-2':'2',
      'p-lg-3':'3',
      'p-lg-4':'4',
      'p-lg-5':'5',
    },
  },
  //---------------------
  xl:{
    label:'All',
    widget:'OpSelect',
    list:{
      'p-xl-0':'0',
      'p-xl-1':'1',
      'p-xl-2':'2',
      'p-xl-3':'3',
      'p-xl-4':'4',
      'p-xl-5':'5',
    },
  },
  //---------------------
}//