export default{
  fieldName:'classList',
  isResponsive:true,
  xs:{
    label:'Top',
    widget:'OpSelect',
    list:{
      'pt-0':'0',
      'pt-1':'1',
      'pt-2':'2',
      'pt-3':'3',
      'pt-4':'4',
      'pt-5':'5',
    },
  },
  //---------------------
  sm:{
    label:'Top',
    widget:'OpSelect',
    list:{
      'pt-sm-0':'0',
      'pt-sm-1':'1',
      'pt-sm-2':'2',
      'pt-sm-3':'3',
      'pt-sm-4':'4',
      'pt-sm-5':'5',
    },
  },
  //---------------------
  md:{
    label:'Top',
    widget:'OpSelect',
    list:{
      'pt-md-0':'0',
      'pt-md-1':'1',
      'pt-md-2':'2',
      'pt-md-3':'3',
      'pt-md-4':'4',
      'pt-md-5':'5',
    },
  },
  //---------------------
  lg:{
    label:'Top',
    widget:'OpSelect',
    list:{
      'pt-lg-0':'0',
      'pt-lg-1':'1',
      'pt-lg-2':'2',
      'pt-lg-3':'3',
      'pt-lg-4':'4',
      'pt-lg-5':'5',
    },
  },
  //---------------------
  xl:{
    label:'Top',
    widget:'OpSelect',
    list:{
      'pt-xl-0':'0',
      'pt-xl-1':'1',
      'pt-xl-2':'2',
      'pt-xl-3':'3',
      'pt-xl-4':'4',
      'pt-xl-5':'5',
    },
  },
  //---------------------
}//<--marginH