export default{
  widget:'OptionRowGroup',
  group:'rowOptions',
  isResponsive:true,
  xs:{
    label:'Align Cols(H)',
    isFirst:true,
    widget:'OpSelect',
    list:{
      'justify-content-start':'Start',
      'justify-content-end':'End',
      'justify-content-center':'Center',
      'justify-content-between':'Between',
      'justify-content-around':'Around',
    },
  },
  //---------------------
  sm:{
    label:'SM',
    widget:'OpSelect',
    list:{
      'justify-content-sm-start':'Start',
      'justify-content-sm-end':'End',
      'justify-content-sm-center':'Center',
      'justify-content-sm-between':'Between',
      'justify-content-sm-around':'Around',
    },
  },
  //---------------------
  md:{
    label:'MD',
    widget:'OpSelect',
    list:{
      'justify-content-md-start':'Start',
      'justify-content-md-end':'End',
      'justify-content-md-center':'Center',
      'justify-content-md-between':'Between',
      'justify-content-md-around':'Around',
    },
  },
  //---------------------
  lg:{
    label:'LG',
    widget:'OpSelect',
    list:{
      'justify-content-lg-start':'Start',
      'justify-content-lg-end':'End',
      'justify-content-lg-center':'Center',
      'justify-content-lg-between':'Between',
      'justify-content-lg-around':'Around',
    },
  },
  //---------------------
  xl:{
    label:'XL',
    widget:'OpSelect',
    list:{
      'justify-content-xl-start':'Start',
      'justify-content-xl-end':'End',
      'justify-content-xl-center':'Center',
      'justify-content-xl-between':'Between',
      'justify-content-xl-around':'Around',
    },
  },
  //---------------------
}//<--hAlign