export default{
  fieldName:'classList',
  isResponsive:true,
  xs:{
    widget:'OpSelect',
    label:'Grow',
    list:{
      'flex-grow-0':'0',
      'flex-grow-1':'1',
    },
  },
  //---------------------
  sm:{
    widget:'OpSelect',
    label:'Grow',
    list:{
      'flex-sm-grow-0':'0',
      'flex-sm-grow-1':'1',
    },
  },
  //---------------------
  md:{
    widget:'OpSelect',
    label:'Grow',
    list:{
      'flex-md-grow-0':'0',
      'flex-md-grow-1':'1',
    },
  },
  //---------------------
  lg:{
    widget:'OpSelect',
    label:'Grow',
    list:{
      'flex-lg-grow-0':'0',
      'flex-lg-grow-1':'1',
    },
  },
  //---------------------
  xl:{
    widget:'OpSelect',
    label:'Grow',
    list:{
      'flex-xl-grow-0':'0',
      'flex-xl-grow-1':'1',
    },
  },
  //---------------------
 }
