export default{
  widget:'OptionRowGroup',
  group:'padding',
  xs:{
    label:'Padding Left',
    isFirst:true,
    widget:'OpSelect',
    list:{
      'pl-0':'0',
      'pl-1':'1',
      'pl-2':'2',
      'pl-3':'3',
      'pl-4':'4',
      'pl-5':'5',
    },
  },
  //---------------------
  sm:{
    label:'SM',
    widget:'OpSelect',
    list:{
      'pl-sm-0':'0',
      'pl-sm-1':'1',
      'pl-sm-2':'2',
      'pl-sm-3':'3',
      'pl-sm-4':'4',
      'pl-sm-5':'5',
    },
  },
  //---------------------
  md:{
    label:'MD',
    widget:'OpSelect',
    list:{
      'pl-md-0':'0',
      'pl-md-1':'1',
      'pl-md-2':'2',
      'pl-md-3':'3',
      'pl-md-4':'4',
      'pl-md-5':'5',
    },
  },
  //---------------------
  lg:{
    label:'LG',
    widget:'OpSelect',
    list:{
      'pl-lg-0':'0',
      'pl-lg-1':'1',
      'pl-lg-2':'2',
      'pl-lg-3':'3',
      'pl-lg-4':'4',
      'pl-lg-5':'5',
    },
  },
  //---------------------
  xl:{
    label:'XL',
    widget:'OpSelect',
    list:{
      'pl-xl-0':'0',
      'pl-xl-1':'1',
      'pl-xl-2':'2',
      'pl-xl-3':'3',
      'pl-xl-4':'4',
      'pl-xl-5':'5',
    },
  },
  //---------------------
}//<--marginH