export default{
  widget:'OptionRowGroup',
  group:'padding',
  xs:{
    label:'Padding(H)',
    isFirst:true,
    widget:'OpSelect',
    list:{
      'px-0':'0',
      'px-1':'1',
      'px-2':'2',
      'px-3':'3',
      'px-4':'4',
      'px-5':'5',
    },
  },
  //---------------------
  sm:{
    label:'SM',
    widget:'OpSelect',
    list:{
      'px-sm-0':'0',
      'px-sm-1':'1',
      'px-sm-2':'2',
      'px-sm-3':'3',
      'px-sm-4':'4',
      'px-sm-5':'5',
    },
  },
  //---------------------
  md:{
    label:'MD',
    widget:'OpSelect',
    list:{
      'px-md-0':'0',
      'px-md-1':'1',
      'px-md-2':'2',
      'px-md-3':'3',
      'px-md-4':'4',
      'px-md-5':'5',
    },
  },
  //---------------------
  lg:{
    label:'LG',
    widget:'OpSelect',
    list:{
      'px-lg-0':'0',
      'px-lg-1':'1',
      'px-lg-2':'2',
      'px-lg-3':'3',
      'px-lg-4':'4',
      'px-lg-5':'5',
    },
  },
  //---------------------
  xl:{
    label:'XL',
    widget:'OpSelect',
    list:{
      'px-xl-0':'0',
      'px-xl-1':'1',
      'px-xl-2':'2',
      'px-xl-3':'3',
      'px-xl-4':'4',
      'px-xl-5':'5',
    },
  },
  //---------------------
}//<--marginH