export default{
  fieldName:'classList',
  isResponsive:true,
  xs:{
    label:'Expand',
    widget:'OpSwitch',
    onValue:'navbar-expand',
    offValue:'',
    defaultValue:'',
  },
  //---------------------
  sm:{
    label:'Expand',
    widget:'OpSwitch',
    onValue:'navbar-expand-sm',
    offValue:'',
    defaultValue:'',
  },
  //---------------------
  md:{
    label:'Expand',
    widget:'OpSwitch',
    onValue:'navbar-expand-md',
    offValue:'',
    defaultValue:'',
  },
  //---------------------
  lg:{
    label:'Expand',
    widget:'OpSwitch',
    onValue:'navbar-expand-lg',
    offValue:'',
    defaultValue:'',
  },
  //---------------------
  xl:{
    label:'Expand',
    widget:'OpSwitch',
    onValue:'navbar-expand-xl',
    offValue:'',
    defaultValue:'',
  },
  //---------------------
}