export default{
  fieldName:'classList',
  isResponsive:true,
  xs:{
    widget:'OpSelect',
    label:'Shrink',
    list:{
      'flex-shrink-0':'0',
      'flex-shrink-1':'1',
    },
  },
  //---------------------
  sm:{
    widget:'OpSelect',
    label:'shrink',
    list:{
      'flex-sm-shrink-0':'0',
      'flex-sm-shrink-1':'1',
    },
  },
  //---------------------
  md:{
    widget:'OpSelect',
    label:'Shrink',
    list:{
      'flex-md-shrink-0':'0',
      'flex-md-shrink-1':'1',
    },
  },
  //---------------------
  lg:{
    widget:'OpSelect',
    label:'Shrink',
    list:{
      'flex-lg-shrink-0':'0',
      'flex-lg-shrink-1':'1',
    },
  },
  //---------------------
  xl:{
    widget:'OpSelect',
    label:'Shrink',
    list:{
      'flex-xl-shrink-0':'0',
      'flex-xl-shrink-1':'1',
    },
  },
  //---------------------
 }
