export default{
  fieldName:'classList',
  isResponsive:true,
  xs:{
    label:'Top',
    widget:'OpSelect',
    list:{
      'mt-0':'0',
      'mt-1':'1',
      'mt-2':'2',
      'mt-3':'3',
      'mt-4':'4',
      'mt-5':'5',
    },
  },
  //---------------------
  sm:{
    label:'Top',
    widget:'OpSelect',
    list:{
      'mt-sm-0':'0',
      'mt-sm-1':'1',
      'mt-sm-2':'2',
      'mt-sm-3':'3',
      'mt-sm-4':'4',
      'mt-sm-5':'5',
    },
  },
  //---------------------
  md:{
    label:'Top',
    widget:'OpSelect',
    list:{
      'mt-md-0':'0',
      'mt-md-1':'1',
      'mt-md-2':'2',
      'mt-md-3':'3',
      'mt-md-4':'4',
      'mt-md-5':'5',
    },
  },
  //---------------------
  lg:{
    label:'Top',
    widget:'OpSelect',
    list:{
      'mt-lg-0':'0',
      'mt-lg-1':'1',
      'mt-lg-2':'2',
      'mt-lg-3':'3',
      'mt-lg-4':'4',
      'mt-lg-5':'5',
    },
  },
  //---------------------
  xl:{
    label:'Top',
    widget:'OpSelect',
    list:{
      'mt-xl-0':'0',
      'mt-xl-1':'1',
      'mt-xl-2':'2',
      'mt-xl-3':'3',
      'mt-xl-4':'4',
      'mt-xl-5':'5',
    },
  },
  //---------------------
}//<--marginH