export default{
  isResponsive:true,
  label:'align',
  xs:{
    valueScope：[
      'text-left', 
      'text-center', 
      'text-right'
    ],
  },
  sm:{
    valueScope：[
      'text-sm-left', 
      'text-sm-center', 
      'text-sm-right'
    ],
  },
  md:{
    valueScope：[
      'text-md-left', 
      'text-md-center', 
      'text-md-right'
    ],
  },
  lg:{
    valueScope：[
      'text-lg-left', 
      'text-lg-center', 
      'text-lg-right'
    ],
  },
  xl:{
    valueScope：[
      'text-xl-left', 
      'text-xl-center', 
      'text-xl-right'
    ],
  },
}
