export default{
  fieldName:'classList',
  isResponsive:true,
  xs:{
    label:'Align',
    widget:'OpSelect',
    list:{
      'text-left':'Left',
      'text-center':'Center',
      'text-right':'Right',
    },
  },
  //---------------------
  sm:{
    label:'Align',
    widget:'OpSelect',
    list:{
      'text-sm-left':'Left',
      'text-sm-center':'Center',
      'text-sm-right':'Right',
    },
  },
  //---------------------
  md:{
    label:'Align',
    widget:'OpSelect',
    list:{
      'text-md-left':'Left',
      'text-md-center':'Center',
      'text-md-right':'Right',
    },
  },
  //---------------------
  lg:{
    label:'Align',
    widget:'OpSelect',
    list:{
      'text-lg-left':'Left',
      'text-lg-center':'Center',
      'text-lg-right':'Right',
    },
  },
  //---------------------
  xl:{
    label:'Align',
    widget:'OpSelect',
    list:{
      'text-xl-left':'Left',
      'text-xl-center':'Center',
      'text-xl-right':'Right',
    },
  },
  //---------------------
}//<--
