import { PageMaterial } from "./Page";
import { IComponentMaterial, Root } from "@rxdrag/react-core";
import { ButtonMaterial, InputMaterial, TextAreaMaterial, InputNumberMaterial, AutoCompleteMaterial, SelectMaterial, CheckboxMaterial, DatePickerMaterial, DateRangePickerMaterial, MentionsMaterial, RadioMaterial, RateMaterial, SliderMaterial, SwitchMaterial, TimePickerMaterial, CascaderMaterial, TransferMaterial, TreeSelectMaterial, TitleMaterial, TextMaterial, LinkMaterial, ParagraphMaterial, StatisticMaterial, IconViewMaterial, AvatarMaterial, BadgeMaterial, ImageViewMaterial, TagMaterial, FormMaterial, InlineFormMaterial, FormItemMaterial, DropdownMaterial, DialogMaterial, DrawerMaterial, PopconfirmMaterial, PopoverMaterial, TooltipMaterial, RowMaterial, ColMaterial, HCFLayoutMaterial, TwoColumnLayoutMaterial, LogoMaterial, MenuMaterial, BoxMaterial, PaperMaterial, DividerMaterial, HeroMaterial, SpaceMaterial, DefaultSlotMaterial, ActionSlotMaterial, ExtraSlotMaterial } from "@rxdrag/react-antd-materials";

export const adminFrameMaterials: IComponentMaterial[] = [
  {
    componentName: "Root",
    component: Root,
    designer: Root,
  },
  PageMaterial,
  ButtonMaterial,
  InputMaterial,
  TextAreaMaterial,
  InputNumberMaterial,
  AutoCompleteMaterial,
  SelectMaterial,
  CheckboxMaterial,
  DatePickerMaterial,
  DateRangePickerMaterial,
  MentionsMaterial,
  RadioMaterial,
  RateMaterial,
  SliderMaterial,
  SwitchMaterial,
  TimePickerMaterial,
  CascaderMaterial,
  TransferMaterial,
  TreeSelectMaterial,
  TitleMaterial,
  TextMaterial,
  LinkMaterial,
  ParagraphMaterial,
  StatisticMaterial,
  IconViewMaterial,
  AvatarMaterial,
  BadgeMaterial,
  ImageViewMaterial,
  TagMaterial,
  FormMaterial,
  InlineFormMaterial,
  FormItemMaterial,
  DropdownMaterial,
  DialogMaterial,
  DrawerMaterial,
  PopconfirmMaterial,
  PopoverMaterial,
  TooltipMaterial,
  RowMaterial,
  ColMaterial,
  HCFLayoutMaterial,
  TwoColumnLayoutMaterial,
  LogoMaterial,
  MenuMaterial,
  BoxMaterial,
  PaperMaterial,
  DividerMaterial,
  HeroMaterial,
  SpaceMaterial,

  //slots
  DefaultSlotMaterial,
  ActionSlotMaterial,
  ExtraSlotMaterial
]