import { PageMaterial } from "./Page";
import { IMaterial } from "@rxdrag/react-core";
import { ButtonMaterial, InputMaterial, TextAreaMaterial, InputNumberMaterial, AutoCompleteMaterial, SelectMaterial, CheckboxMaterial, DatePickerMaterial, DateRangePickerMaterial, MentionsMaterial, RadioMaterial, RateMaterial, SliderMaterial, SwitchMaterial, TimePickerMaterial, CascaderMaterial, TransferMaterial, TreeSelectMaterial, TitleMaterial, TextMaterial, LinkMaterial, ParagraphMaterial, StatisticMaterial, IconViewMaterial, AvatarMaterial, BadgeMaterial, ImageViewMaterial, TagMaterial, FormMaterial, InlineFormMaterial, FormItemMaterial, DropdownMaterial, DialogGroupMaterial, DrawerGroupMaterial, PopconfirmMaterial, PopoverMaterial, TooltipMaterial, RowMaterial, ColMaterial, HCFLayoutMaterial, TwoColumnLayoutMaterial, LogoMaterial, BoxMaterial, PaperMaterial, DividerMaterial, HeroMaterial, SpaceMaterial, DefaultSlotMaterial, ActionSlotMaterial, ExtraSlotMaterial, FormLayoutMaterial, ContainerMaterial } from "@rxdrag/react-antd-materials";
import { AppMaterial } from "./App";
import { MenuMaterial } from "./Menu";

export const adminFrameMaterials: IMaterial[] = [
  AppMaterial,
  ContainerMaterial,
  PageMaterial,
  ButtonMaterial,
  InputMaterial,
  TextAreaMaterial,
  InputNumberMaterial,
  AutoCompleteMaterial,
  SelectMaterial,
  CheckboxMaterial,
  DatePickerMaterial,
  DateRangePickerMaterial,
  MentionsMaterial,
  RadioMaterial,
  RateMaterial,
  SliderMaterial,
  SwitchMaterial,
  TimePickerMaterial,
  CascaderMaterial,
  TransferMaterial,
  TreeSelectMaterial,
  TitleMaterial,
  TextMaterial,
  LinkMaterial,
  ParagraphMaterial,
  StatisticMaterial,
  IconViewMaterial,
  AvatarMaterial,
  BadgeMaterial,
  ImageViewMaterial,
  TagMaterial,
  FormMaterial,
  FormLayoutMaterial,
  InlineFormMaterial,
  FormItemMaterial,
  DropdownMaterial,
  DialogGroupMaterial,
  DrawerGroupMaterial,
  PopconfirmMaterial,
  PopoverMaterial,
  TooltipMaterial,
  RowMaterial,
  ColMaterial,
  HCFLayoutMaterial,
  TwoColumnLayoutMaterial,
  LogoMaterial,
  MenuMaterial,
  BoxMaterial,
  PaperMaterial,
  DividerMaterial,
  HeroMaterial,
  SpaceMaterial,

  //slots
  DefaultSlotMaterial,
  ActionSlotMaterial,
  ExtraSlotMaterial
]