export default{
  fieldName:'classList',
  isResponsive:true,
  xs:{
    label:'Vertical',
    widget:'OpSelect',
    list:{
      'py-0':'0',
      'py-1':'1',
      'py-2':'2',
      'py-3':'3',
      'py-4':'4',
      'py-5':'5',
    },
  },
  //---------------------
  sm:{
    label:'Vertical',
    widget:'OpSelect',
    list:{
      'py-sm-0':'0',
      'py-sm-1':'1',
      'py-sm-2':'2',
      'py-sm-3':'3',
      'py-sm-4':'4',
      'py-sm-5':'5',
    },
  },
  //---------------------
  md:{
    label:'Vertical',
    widget:'OpSelect',
    list:{
      'py-md-0':'0',
      'py-md-1':'1',
      'py-md-2':'2',
      'py-md-3':'3',
      'py-md-4':'4',
      'py-md-5':'5',
    },
  },
  //---------------------
  lg:{
    label:'Vertical',
    widget:'OpSelect',
    list:{
      'py-lg-0':'0',
      'py-lg-1':'1',
      'py-lg-2':'2',
      'py-lg-3':'3',
      'py-lg-4':'4',
      'py-lg-5':'5',
    },
  },
  //---------------------
  xl:{
    label:'Vertical',
    widget:'OpSelect',
    list:{
      'py-xl-0':'0',
      'py-xl-1':'1',
      'py-xl-2':'2',
      'py-xl-3':'3',
      'py-xl-4':'4',
      'py-xl-5':'5',
    },
  },
  //---------------------
}//<--marginV
